// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLxAgvIVrG5AjuO6iZnUa3Y0Ls62q8lyw',
    appId: '1:837503318475:web:0c3ede4ec6715f42699e4e',
    messagingSenderId: '837503318475',
    projectId: 'fourthyearproject-2468e',
    authDomain: 'fourthyearproject-2468e.firebaseapp.com',
    databaseURL: 'https://fourthyearproject-2468e-default-rtdb.firebaseio.com',
    storageBucket: 'fourthyearproject-2468e.appspot.com',
    measurementId: 'G-DSQRS97Q42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8n5FXd4goewrQhujpLGfsBBUSZsVGGMk',
    appId: '1:837503318475:android:bc00ee7ed9357033699e4e',
    messagingSenderId: '837503318475',
    projectId: 'fourthyearproject-2468e',
    databaseURL: 'https://fourthyearproject-2468e-default-rtdb.firebaseio.com',
    storageBucket: 'fourthyearproject-2468e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8OjT74TGUz0FDQ3b7-9MjTxFwze_Elx4',
    appId: '1:837503318475:ios:4be25a2aadc5a53d699e4e',
    messagingSenderId: '837503318475',
    projectId: 'fourthyearproject-2468e',
    databaseURL: 'https://fourthyearproject-2468e-default-rtdb.firebaseio.com',
    storageBucket: 'fourthyearproject-2468e.appspot.com',
    iosClientId: '837503318475-p1mluucheqh6kf2ej2ua1qjj1c8qefka.apps.googleusercontent.com',
    iosBundleId: 'com.aasharef.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8OjT74TGUz0FDQ3b7-9MjTxFwze_Elx4',
    appId: '1:837503318475:ios:7d310ded121ec7ce699e4e',
    messagingSenderId: '837503318475',
    projectId: 'fourthyearproject-2468e',
    databaseURL: 'https://fourthyearproject-2468e-default-rtdb.firebaseio.com',
    storageBucket: 'fourthyearproject-2468e.appspot.com',
    iosClientId: '837503318475-a8svo2168mrqh1ib5b6ie93cj1k6keel.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
